### PR TITLE
Added Weeks selection step / filter by weeks.

### PR DESCRIPTION
**Pull request by duozersk**
Camp Finder is implemented in AF3 by separate module/paragraph. In AF4 we have added the Weeks filter checkbox - the idea is to change/replace the dates/times selection/filter by the Weeks selection/filter.

https://ymcagbw.org/camp-finder-4-test-page

image

image

image

### CODE REVIEW

**Comment by duozersk** [comment]
This one requires rebase and we should be careful with searchParams - see #39

**Comment by duozersk** [comment]
Rebased and re-compiled. Should be good to go.

**Review by podarok — APPROVED** [review]
technically this is good. Let's approve @sarah-halby

**Comment by duozersk** [comment]
Removed the compiled artifacts changes to not have conflicts after other PR merges. Requires app compilation before merge.

**Comment by podarok** [comment]
This is disabled by default and we had a conversation with Sarah - approved to merge.

**Pull request merged**
